/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppearancePanel: typeof import('./../components/settings/AppearancePanel.vue')['default']
    AppLogo: typeof import('./../components/common/AppLogo.vue')['default']
    BackupSelectionForm: typeof import('./../components/backup/BackupSelectionForm.vue')['default']
    BranchCard: typeof import('./../components/result/BranchCard.vue')['default']
    ColorRectPicker: typeof import('./../components/settings/ColorRectPicker.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EulaDialog: typeof import('./../components/common/EulaDialog.vue')['default']
    ExcelPanel: typeof import('./../components/excel/ExcelPanel.vue')['default']
    ExplanationPanel: typeof import('./../components/llm/ExplanationPanel.vue')['default']
    ExportDialog: typeof import('./../components/report/ExportDialog.vue')['default']
    ExportLocationPicker: typeof import('./../components/report/ExportLocationPicker.vue')['default']
    ExportOptionsForm: typeof import('./../components/settings/ExportOptionsForm.vue')['default']
    FormulaHeader: typeof import('./../components/formula/FormulaHeader.vue')['default']
    FormulaRow: typeof import('./../components/common/FormulaRow.vue')['default']
    GalleryPicker: typeof import('./../components/image/GalleryPicker.vue')['default']
    ImageAttachRow: typeof import('./../components/image/ImageAttachRow.vue')['default']
    ImageCachePanel: typeof import('./../components/image/ImageCachePanel.vue')['default']
    ImageViewer: typeof import('./../components/image/ImageViewer.vue')['default']
    ImportConfirmDialog: typeof import('./../components/backup/ImportConfirmDialog.vue')['default']
    InputHistoryButton: typeof import('./../components/common/InputHistoryButton.vue')['default']
    MarkdownText: typeof import('./../components/llm/MarkdownText.vue')['default']
    MathDisplay: typeof import('./../components/math/MathDisplay.vue')['default']
    MathNodeView: typeof import('./../components/math/MathNodeView.vue')['default']
    ModelProfileForm: typeof import('./../components/settings/ModelProfileForm.vue')['default']
    ModelProfileList: typeof import('./../components/settings/ModelProfileList.vue')['default']
    MultiResultTable: typeof import('./../components/result/MultiResultTable.vue')['default']
    NavIcon: typeof import('./../components/common/NavIcon.vue')['default']
    OperatorQuickInsert: typeof import('./../components/formula/OperatorQuickInsert.vue')['default']
    ParamField: typeof import('./../components/formula/ParamField.vue')['default']
    ParamForm: typeof import('./../components/formula/ParamForm.vue')['default']
    ProgressPanel: typeof import('./../components/backup/ProgressPanel.vue')['default']
    PromptEditor: typeof import('./../components/settings/PromptEditor.vue')['default']
    RefineDialog: typeof import('./../components/llm/RefineDialog.vue')['default']
    RemoteFileList: typeof import('./../components/webdav/RemoteFileList.vue')['default']
    ReportPreview: typeof import('./../components/report/ReportPreview.vue')['default']
    ResetPanel: typeof import('./../components/settings/ResetPanel.vue')['default']
    ResultPanel: typeof import('./../components/result/ResultPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./../components/layout/SideNav.vue')['default']
    SourceBadge: typeof import('./../components/common/SourceBadge.vue')['default']
    StepsList: typeof import('./../components/steps/StepsList.vue')['default']
    StickyHeader: typeof import('./../components/common/StickyHeader.vue')['default']
    ThinkingBox: typeof import('./../components/llm/ThinkingBox.vue')['default']
    TokenStatGrid: typeof import('./../components/settings/TokenStatGrid.vue')['default']
    TopBar: typeof import('./../components/layout/TopBar.vue')['default']
    VersionDiff: typeof import('./../components/version/VersionDiff.vue')['default']
    WebDavConfigForm: typeof import('./../components/webdav/WebDavConfigForm.vue')['default']
  }
}
